### ISSUE TITLE
Find a faster way to encode (read: decode) geometry blob

### ISSUE THREAD

**Issue by straup** [whosonfirst/go-whosonfirst-spatial-sqlite#4]
Unmarshal-ing coordinate blobs from JSON is where things slow down. Is there a better way to encode things?

Encoding happens here (in a different package):

https://github.com/whosonfirst/go-whosonfirst-sqlite-features/blob/master/tables/rtree.go#L207-L217

Decoding happens here:

https://github.com/whosonfirst/go-whosonfirst-spatial-sqlite/blob/main/database.go#L438-L451

**Comment by thisisaaronland** [comment]
https://github.com/pquerna/ffjson does not appear to be any faster and in many cases, actually slower.

**Comment by thisisaaronland** [comment]
Maybe `fastjson` ?

https://godoc.org/github.com/valyala/fastjson#example-Parser-Parse

**Comment by straup** [comment]
Not sure if this is still relevant not that `paulmach/orb` is being used for operations. Closing for now.
